services:
  ei-video-classification-runner:
    image: ${DOCKER_REGISTRY_BASE:-ghcr.io/arduino/}app-bricks/ei-models-runner:0.7.0
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"      
    ports:
      - ${BIND_ADDRESS:-0.0.0.0}:5050:5050  # TCP input for video frames
      - ${BIND_ADDRESS:-0.0.0.0}:4912:4912  # Embedded UI port
    volumes:
      - "${CUSTOM_MODEL_PATH:-/home/arduino/.arduino-bricks}:${CUSTOM_MODEL_PATH:-/home/arduino/.arduino-bricks}"
      - "/run/udev:/run/udev"
    command: ["--model-file", "${EI_V_CLASSIFICATION_MODEL:-/models/ootb/ei/mobilenet-v2-224px.eim}", "--dont-print-predictions", "--mode", "streaming-tcp-server", "--preview-original-resolution"]
    healthcheck:
      test: [ "CMD-SHELL", "netstat -tuln | grep :5050 || exit 1" ]
      interval: 2s
      timeout: 2s
      retries: 25
