services:
  ei-video-obj-detection-runner:
    image: ${DOCKER_REGISTRY_BASE:-ghcr.io/arduino/}app-bricks/ei-models-runner:0.7.1
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"     
    ports:
      - ${BIND_ADDRESS:-0.0.0.0}:5050:5050  # TCP input for video frames
      - ${BIND_ADDRESS:-0.0.0.0}:4912:4912  # Embedded UI port
    volumes:
      - "${CUSTOM_MODEL_PATH:-/home/arduino/.arduino-bricks}:${CUSTOM_MODEL_PATH:-/home/arduino/.arduino-bricks}"
      - "/run/udev:/run/udev"
    command: ["--model-file", "${EI_V_OBJ_DETECTION_MODEL:-/models/ootb/ei/yolo-x-nano.eim}", "--gst-source", "tcpserversrc host=0.0.0.0 port=5050 ! jpegdec", "--dont-print-predictions", "--preview-original-resolution"]
    healthcheck:
      test: [ "CMD-SHELL", "netstat -tuln | grep :5050 || exit 1" ]
      interval: 2s
      timeout: 2s
      retries: 25
